### ISSUE TITLE
How to convert result of this tool(hald image) to 2D Square CLUT 512?

### ISSUE THREAD

**Issue by zhuhuihuihui** [homm/color-transformations-reconstruction#13]
The framework that I'm using does not recognize hald image, it only takes 2D CLUTs in 512 size. Example:

![](https://www.emanueleferonato.com/wp-content/uploads/2018/06/download-1.png)

Any idea how I can convert you hald images to 2D CLUTs?

Thanks

**Comment by AlexDaniel** [comment]
Easy, you just take a neutral (original) LUT file and then use imagemagick to apply the generated LUT on it.

I think this is the original lut file you're looking for:
![obs-original](https://user-images.githubusercontent.com/5507503/50051039-fdc38880-0112-11e9-8e20-68eb8712999a.png)

**Comment by homm** [comment]
You can use the following python code (you'll need OpenCV and NumPy installed):

```python
import numpy, cv2

hald = cv2.imread('1.Clarendon.png')

size = int(hald.shape[0] ** (1.0/3.0) + .5)
clut = numpy.concatenate([
    numpy.concatenate(im.reshape((size, size, size**2, size**2, 3))[row], axis=1)
    for row in range(size)
])

cv2.imwrite("clut.png", clut)
```

![1 Clarendon](https://user-images.githubusercontent.com/128982/55878223-ad31d880-5ba4-11e9-8309-6a59b67661cd.png) ![_out](https://user-images.githubusercontent.com/128982/55878225-af943280-5ba4-11e9-9336-3e48ba275df0.png)

**Comment by sinanhlvc** [comment]
> You can use the following python code (you'll need OpenCV and NumPy installed):
> 
> ```python
> import numpy, cv2
> 
> hald = cv2.imread('1.Clarendon.png')
> 
> size = int(hald.shape[0] ** (1.0/3.0) + .5)
> clut = numpy.concatenate([
>     numpy.concatenate(im.reshape((size, size, size**2, size**2, 3))[row], axis=1)
>     for row in range(size)
> ])
> 
> cv2.imwrite("clut.png", clut)
> ```
> 
> ![1 Clarendon](https://user-images.githubusercontent.com/128982/55878223-ad31d880-5ba4-11e9-8309-6a59b67661cd.png) ![_out](https://user-images.githubusercontent.com/128982/55878225-af943280-5ba4-11e9-9336-3e48ba275df0.png)

Hi @homm! Sorry for the very late bump. I have been struggling with HaldClut for two days now. My question is unrelated, but I am looking for the reverse version of this script. I need to convert the square 512 HaldClut to the format this program outputs. Could you help me with it, if possible? Thank you so much!

**Comment by homm** [comment]
@SinanHlvc I really sorry, I'm not working with numpy all the time and after a year it is hard to say how exactly I achieved the result as well as write a reverted version. It will be faster to ask on Stackoverflow.
