### ISSUE TITLE
How to adjust the filter level

### ISSUE THREAD

**Issue by lrhehe** [homm/color-transformations-reconstruction#14]
Is there any solution to adjust filter level? 

One brute-force way is generating 100 CLUTs according to filter level 1-100
Is there any better one?

**Comment by homm** [comment]
I don't know how exactly Instagram measures "intensity" of the filters but for simple linear scale you can use [amplify_lut](https://pillow-lut-tools.readthedocs.io/en/latest/#pillow_lut.amplify_lut) function from [pillow-lut-tools](https://github.com/homm/pillow-lut-tools) package with a scale from 0 to 1 or even beyond this range.

**Comment by lrhehe** [comment]
thanks, I will try this.
another linear solution: originColor * (1 - intensity) + filteredColor * intensity
