### ISSUE TITLE
how to generate new raw lut file in different color-style

### ISSUE THREAD

**Issue by bladezhang** [homm/color-transformations-reconstruction#16]
how to generate new raw lut png file in different color-style  except existed file such as 0.original.png  1.Clarendon.jpg 3.Moon.jpg 15.Hudson.jpg

this reverse engineering  shows me how to use the existed filter but doesn't show how to generate filter from image

**Comment by homm** [comment]
Have you tried the guide? https://github.com/homm/color-filters-reconstruction#guide
